Convert *_INTERVAL variables to int
ALERT_INTERVAL and NOTIFICATION_INTERVAL are now converted to
numbers. This allows user-defined ALERT_INTERVAL and
NOTIFICATION_INTERVAL env variables to work without throwing
TypeErrors:

    return self.run(*args, **kwargs)
  File "/cabot/cabot/cabotapp/tasks.py", line 68, in update_service
    service.update_status()
  File "/cabot/cabot/cabotapp/models.py", line 243, in update_status
    self.alert()
  File "/cabot/cabot/cabotapp/models.py", line 174, in alert
    if self.last_alert_sent and (timezone.now() - timedelta(minutes=settings.ALERT_INTERVAL)) < self.last_alert_sent:
TypeError: unsupported type for timedelta minutes component: str