Create Django super user after running DB migrations
After my change to automatically create UserProfiles, newly provisioned
instances were failing on this:

    django.db.utils.ProgrammingError: relation "cabotapp_userprofile" does not exist

This change addresses that problem by creating the superuser account
after the DB migrations are run.